prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/apex_5_administration_header.sql
@@application/shared_components/navigation/lists/apex_5_help.sql
@@application/shared_components/navigation/lists/apex_ci_cd_tabs.sql
@@application/shared_components/files/custom_css.sql
@@application/shared_components/files/custom_css_map.sql
@@application/shared_components/files/custom_min_css.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/flow_admin.sql
@@application/shared_components/security/authorizations/user_is_a_developer.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/apex_5_0_no_side_bar.sql
@@application/shared_components/user_interface/templates/page/apex_5_0_right_side_bar.sql
@@application/shared_components/user_interface/templates/page/apex_rw_faceted_search.sql
@@application/shared_components/user_interface/templates/page/apex_5_0_dialog.sql
@@application/shared_components/user_interface/templates/page/apex_5_0_edit_screen.sql
@@application/shared_components/user_interface/templates/page/apex_5_0_wizard_dialog.sql
@@application/shared_components/user_interface/templates/page/apex_5_0_wizard.sql
@@application/shared_components/user_interface/templates/page/done_popup.sql
@@application/shared_components/user_interface/templates/button/apex_4_0_next_gray_bg.sql
@@application/shared_components/user_interface/templates/button/apex_4_0_previous_gray_bg.sql
@@application/shared_components/user_interface/templates/button/apex_4_1_button.sql
@@application/shared_components/user_interface/templates/button/apex_4_2_icon_button.sql
@@application/shared_components/user_interface/templates/button/apex_4_2_next_button.sql
@@application/shared_components/user_interface/templates/button/apex_4_2_previous_button.sql
@@application/shared_components/user_interface/templates/button/apex_5_0_button.sql
@@application/shared_components/user_interface/templates/button/apex_5_0_button_with_icon.sql
@@application/shared_components/user_interface/templates/button/apex_5_0_icon_menu_button.sql
@@application/shared_components/user_interface/templates/button/apex_5_0_icon_only_button.sql
@@application/shared_components/user_interface/templates/button/html_button_legacy_apex_5_migration.sql
@@application/shared_components/user_interface/templates/button/html_image_legacy_apex_5_migration.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_div_with_id_c_htmldbhid.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_div_with_id_c_htmldbhid_002.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_button_region.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_region_top_buttons.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_region_with_icon.sql
@@application/shared_components/user_interface/templates/region/loading_region_hidden_by_default.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_hide_and_show_region_2.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_div_float_left.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_div_with_id_and_region_attributes.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_hide_and_show_region.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_reports_region.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_reports_region_002.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_rounded_corner_large.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_rounded_corner_large_002.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_rounded_corner_small_blue_top.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_rounded_corner_small_gray_top.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_sidebar_gray_header.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_sidebar_gray_header_002.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_sidebar_navigation.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_top_bar_100.sql
@@application/shared_components/user_interface/templates/region/apex_4_0_wizard_box_wide.sql
@@application/shared_components/user_interface/templates/region/apex_4_2_action_box.sql
@@application/shared_components/user_interface/templates/region/apex_4_2_action_box_002.sql
@@application/shared_components/user_interface/templates/region/apex_4_2_action_box_confirm.sql
@@application/shared_components/user_interface/templates/region/apex_4_2_action_box_confirm_002.sql
@@application/shared_components/user_interface/templates/region/apex_4_2_action_box_confirm_003.sql
@@application/shared_components/user_interface/templates/region/apex_4_2_wizard_body.sql
@@application/shared_components/user_interface/templates/region/apex_4_2_wizard_body_divider.sql
@@application/shared_components/user_interface/templates/region/apex_4_2_wizard_body_hide_show.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_alert.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_div_with_id_class_and_region_attributes.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_hide_show_region.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_interactive_report_region.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_message_region.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_page_anchors.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_processing_spinner_region.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_region.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_wizard_body_hide_show.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_wizard_header.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_wizard_region.sql
@@application/shared_components/user_interface/templates/region/apex_5_0_wizard_title_region.sql
@@application/shared_components/user_interface/templates/list/apex_4_2_wizard_progress_bar.sql
@@application/shared_components/user_interface/templates/list/apex_5_0_image_navigation.sql
@@application/shared_components/user_interface/templates/list/apex_5_0_media_list.sql
@@application/shared_components/user_interface/templates/list/apex_5_0_menu_popup.sql
@@application/shared_components/user_interface/templates/list/apex_5_0_navigation_list.sql
@@application/shared_components/user_interface/templates/list/apex_5_0_sub_tabs.sql
@@application/shared_components/user_interface/templates/list/apex_5_0_sub_tabs_002.sql
@@application/shared_components/user_interface/templates/list/apex_5_0_wizard_progress.sql
@@application/shared_components/user_interface/templates/list/apex_standard_tabs_with_pull_down.sql
@@application/shared_components/user_interface/templates/list/simple_image_list.sql
@@application/shared_components/user_interface/templates/list/eba_large_icons_list.sql
@@application/shared_components/user_interface/templates/list/horizontal_with_images.sql
@@application/shared_components/user_interface/templates/list/apex_5_0_links_list.sql
@@application/shared_components/user_interface/templates/list/apex_5_0_links_list_002.sql
@@application/shared_components/user_interface/templates/list/apex_5_0_links_list_003.sql
@@application/shared_components/user_interface/templates/report/dhtml_automatic_ppr_pagination_report_from_4999.sql
@@application/shared_components/user_interface/templates/report/apex_4_1_eba_standard_report.sql
@@application/shared_components/user_interface/templates/report/vertical_plain_c_htmldbverticalregion.sql
@@application/shared_components/user_interface/templates/report/apex_4_0_portlet_report.sql
@@application/shared_components/user_interface/templates/report/apex_4_0_portlet_row_template.sql
@@application/shared_components/user_interface/templates/report/2_dhtml_automatic_ppr_pagination_report_from_4999.sql
@@application/shared_components/user_interface/templates/report/apex_5_0_badge_list_named_column.sql
@@application/shared_components/user_interface/templates/report/apex_5_0_badge_list_row.sql
@@application/shared_components/user_interface/templates/report/apex_5_0_links_list.sql
@@application/shared_components/user_interface/templates/report/apex_5_0_portlet_column_template.sql
@@application/shared_components/user_interface/templates/report/apex_5_0_portlet_row_template.sql
@@application/shared_components/user_interface/templates/report/apex_5_0_standard_report.sql
@@application/shared_components/user_interface/templates/report/apex_4_0_standard_report.sql
@@application/shared_components/user_interface/templates/label/done_label_optional_no_link.sql
@@application/shared_components/user_interface/templates/label/apex_5_0_dynamic_attribute.sql
@@application/shared_components/user_interface/templates/label/apex_5_0_hidden_label.sql
@@application/shared_components/user_interface/templates/label/apex_5_0_optional_label.sql
@@application/shared_components/user_interface/templates/label/apex_5_0_optional_label_above.sql
@@application/shared_components/user_interface/templates/label/apex_5_0_required_label.sql
@@application/shared_components/user_interface/templates/label/apex_5_0_required_label_above.sql
@@application/shared_components/user_interface/templates/label/dynamic_attribute.sql
@@application/shared_components/user_interface/templates/label/form_field_optional.sql
@@application/shared_components/user_interface/templates/label/hidden_label_read_by_screen_reader.sql
@@application/shared_components/user_interface/templates/label/label_tag_only.sql
@@application/shared_components/user_interface/templates/label/f_fromfield_required.sql
@@application/shared_components/user_interface/templates/label/htmldb_greenarealabel_c_htmldbgalabel.sql
@@application/shared_components/user_interface/templates/breadcrumb/apex_5_0_breadcrumbs.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumbs.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/htmldb_calendar_from_4350.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/plugins/authorization_type/com_oracle_apex_developer_authorization.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00006.sql
@@application/pages/page_00101.sql
@@application/pages/page_09999.sql
@@application/end_environment.sql
